let currentSchedule = null;
const $ = id => document.getElementById(id);
function todayISO(){ const d=new Date(); const local=new Date(d.getTime()-d.getTimezoneOffset()*60000); return local.toISOString().slice(0,10); }
async function api(url, options={}){ const response=await fetch(url,{headers:{"Content-Type":"application/json"},...options}); const data=await response.json(); if(!response.ok) throw new Error(data.detail||"Request failed"); return data; }
function showMessage(text,type=""){ $("message").textContent=text; $("message").className="message "+type; }
function escapeHtml(v){ return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"); }
function renderTasks(tasks){ const root=$("tasks"); if(!tasks.length){root.innerHTML='<div class="empty">No pending tasks.</div>';return;} root.innerHTML=tasks.map(t=>`<div class="task"><div><strong>${escapeHtml(t.title)}</strong><div class="muted">${t.duration} min • deadline ${t.deadline||"none"}</div></div><div class="task-right"><span class="priority ${t.priority}">${t.priority}</span><button class="delete" onclick="deleteTask(${t.id})">×</button></div></div>`).join(""); }
async function loadTasks(){ renderTasks(await api("/api/tasks")); }
async function loadState(){ const s=await api("/api/state"); $("connection").textContent=s.google_calendar_connected?"Google Calendar connected":"Local calendar mode"; $("connection").className=s.google_calendar_connected?"status connected":"status"; $("calendarSource").textContent=s.google_calendar_connected?"Google Calendar":"Local demo calendar"; }
async function deleteTask(id){await api(`/api/tasks/${id}`,{method:"DELETE"});await loadTasks();}
async function addTask(){ const title=$("taskTitle").value.trim(); if(!title)return showMessage("Enter a task title.","error"); await api("/api/tasks",{method:"POST",body:JSON.stringify({title,priority:$("taskPriority").value,duration:Number($("taskDuration").value),deadline:$("taskDeadline").value||null,description:""})}); $("taskTitle").value="";showMessage("Task added.","success");await loadTasks(); }
function renderSchedule(s){ $("schedule").className="schedule"; $("schedule").innerHTML=s.events.map(e=>`<div class="event ${e.event_type}"><div class="time">${e.start_time}<br><span>to</span><br>${e.end_time}</div><div class="event-main"><strong>${escapeHtml(e.activity)}</strong><span>${escapeHtml(e.event_type)} • ${escapeHtml(e.priority)}</span><p>${escapeHtml(e.reason)}</p></div></div>`).join(""); }
async function generatePlan(){ const date=$("date").value;if(!date)return showMessage("Choose a date.","error");$("planBtn").disabled=true;$("planBtn").textContent="Planning…";showMessage("Agent is gathering context and building the schedule…");try{const r=await api("/api/plan",{method:"POST",body:JSON.stringify({date,request:$("request").value})});currentSchedule=r.schedule;renderSchedule(currentSchedule);$("reasoning").textContent=r.agent_reasoning||"No reasoning summary returned.";$("validation").textContent="✓ Deterministic validation passed";$("validation").className="valid";$("approveBtn").disabled=false;$("calendarSource").textContent=r.calendar_source==="google"?"Google Calendar":"Local demo calendar";showMessage("Schedule generated successfully.","success");}catch(e){showMessage(e.message,"error");}finally{$("planBtn").disabled=false;$("planBtn").textContent="Generate Schedule";}}
async function approveSchedule(){if(!currentSchedule)return;$("approveBtn").disabled=true;try{const r=await api("/api/approve",{method:"POST",body:JSON.stringify({date:currentSchedule.date,schedule:currentSchedule})});showMessage(`Approved and saved. ${r.google_events_created} Google Calendar events created.`,"success");}catch(e){showMessage(e.message,"error");$("approveBtn").disabled=false;}}
$("date").value=todayISO();$("refreshBtn").onclick=loadTasks;$("addTaskBtn").onclick=addTask;$("planBtn").onclick=generatePlan;$("approveBtn").onclick=approveSchedule;$("googleBtn").onclick=()=>window.location.href="/api/auth/google";loadTasks();loadState();
